Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -49,6 +49,7 @@ jobs:
           echo "Build status: $build_failed"
 
       - name: Test all projects
+        continue-on-error: true
         run: |
           test_failed=false
 
@@ -56,21 +57,20 @@ jobs:
 
           for test_project in "${test_projects[@]}"; do
             echo "Running tests for: \"$test_project\""
-            test_output=$(dotnet test "$test_project" --no-restore --no-build --logger trx || true)
+            test_output=$(dotnet test "$test_project" --no-restore --no-build --logger "console;verbosity=normal" || true)
 
             if [[ $test_output == *"Failed!"* ]]; then
               test_failed=true
-              while IFS= read -r line; do
-                if [[ "$line" =~ ([^:]+):([0-9]+):\ error:\ (.*) ]]; then
-                  file="${BASH_REMATCH[1]}"
-                  line_number="${BASH_REMATCH[2]}"
-                  error_message="${BASH_REMATCH[3]}"
-                  echo "::error file=$file,line=$line_number::$error_message"
-                fi
-              done <<< "$test_output"
             fi
 
-            echo "$test_output"
+            echo "$test_output" | awk '!seen[$0]++' | while read -r line; do
+              if [[ "$line" =~ ([^:]+):([0-9]+):\ error:\ (.*) ]]; then
+                file="${BASH_REMATCH[1]}"
+                line_number="${BASH_REMATCH[2]}"
+                error_message="${BASH_REMATCH[3]}"
+                echo "::error file=$file,line=$line_number::$error_message"
+              fi
+            done
           done
 
           echo "test_failed=$test_failed" >> $GITHUB_ENV
